package com.tvz.mobilnelabapi.mappers.dao;

import com.tvz.mobilnelabapi.model.Authority;
import com.tvz.mobilnelabapi.model.AuthorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface AuthorityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tvz.authority
	 * 
	 * @mbg.generated Thu Jul 26 22:42:58 CEST 2018
	 */
	@SelectProvider(type = AuthoritySqlProvider.class, method = "countByExample")
	long countByExample(AuthorityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tvz.authority
	 * 
	 * @mbg.generated Thu Jul 26 22:42:58 CEST 2018
	 */
	@DeleteProvider(type = AuthoritySqlProvider.class, method = "deleteByExample")
	int deleteByExample(AuthorityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tvz.authority
	 * 
	 * @mbg.generated Thu Jul 26 22:42:58 CEST 2018
	 */
	@Delete({ "delete from tvz.authority", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tvz.authority
	 * 
	 * @mbg.generated Thu Jul 26 22:42:58 CEST 2018
	 */
	@Insert({ "insert into tvz.authority (id, name)", "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR})" })
	int insert(Authority record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tvz.authority
	 * 
	 * @mbg.generated Thu Jul 26 22:42:58 CEST 2018
	 */
	@InsertProvider(type = AuthoritySqlProvider.class, method = "insertSelective")
	int insertSelective(Authority record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tvz.authority
	 * 
	 * @mbg.generated Thu Jul 26 22:42:58 CEST 2018
	 */
	@SelectProvider(type = AuthoritySqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR) })
	List<Authority> selectByExampleWithRowbounds(AuthorityExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tvz.authority
	 * 
	 * @mbg.generated Thu Jul 26 22:42:58 CEST 2018
	 */
	@SelectProvider(type = AuthoritySqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR) })
	List<Authority> selectByExample(AuthorityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tvz.authority
	 * 
	 * @mbg.generated Thu Jul 26 22:42:58 CEST 2018
	 */
	@Select({ "select", "id, name", "from tvz.authority", "where id = #{id,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR) })
	Authority selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tvz.authority
	 * 
	 * @mbg.generated Thu Jul 26 22:42:58 CEST 2018
	 */
	@UpdateProvider(type = AuthoritySqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") Authority record, @Param("example") AuthorityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tvz.authority
	 * 
	 * @mbg.generated Thu Jul 26 22:42:58 CEST 2018
	 */
	@UpdateProvider(type = AuthoritySqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") Authority record, @Param("example") AuthorityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tvz.authority
	 * 
	 * @mbg.generated Thu Jul 26 22:42:58 CEST 2018
	 */
	@UpdateProvider(type = AuthoritySqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Authority record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table tvz.authority
	 * 
	 * @mbg.generated Thu Jul 26 22:42:58 CEST 2018
	 */
	@Update({ "update tvz.authority", "set name = #{name,jdbcType=VARCHAR}", "where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Authority record);

	@Select({ "select", "name", "from tvz.authority authority",
			"inner join tvz.user_authority userauthority ON userauthority.authority_id = authority.id ",
			"where userauthority.user_id = #{id,jdbcType=INTEGER}" })
	@Results({ @Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR) })
	List<String> selectAuthorityByUserId(Integer id);

}