package com.tvz.mobilnelabapi.mappers.dao;

import com.tvz.mobilnelabapi.model.Device;
import com.tvz.mobilnelabapi.model.DeviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface DeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.Device
     *
     * @mbg.generated Sun Jul 29 14:44:38 CEST 2018
     */
    @SelectProvider(type=DeviceSqlProvider.class, method="countByExample")
    long countByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.Device
     *
     * @mbg.generated Sun Jul 29 14:44:38 CEST 2018
     */
    @DeleteProvider(type=DeviceSqlProvider.class, method="deleteByExample")
    int deleteByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.Device
     *
     * @mbg.generated Sun Jul 29 14:44:38 CEST 2018
     */
    @Delete({
        "delete from mob.Device",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.Device
     *
     * @mbg.generated Sun Jul 29 14:44:38 CEST 2018
     */
    @Insert({
        "insert into mob.Device (ID, Name, ",
        "Description)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR})"
    })
    int insert(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.Device
     *
     * @mbg.generated Sun Jul 29 14:44:38 CEST 2018
     */
    @InsertProvider(type=DeviceSqlProvider.class, method="insertSelective")
    int insertSelective(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.Device
     *
     * @mbg.generated Sun Jul 29 14:44:38 CEST 2018
     */
    @SelectProvider(type=DeviceSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="Name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="Description", property="description", jdbcType=JdbcType.VARCHAR)
    })
    List<Device> selectByExampleWithRowbounds(DeviceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.Device
     *
     * @mbg.generated Sun Jul 29 14:44:38 CEST 2018
     */
    @SelectProvider(type=DeviceSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="Name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="Description", property="description", jdbcType=JdbcType.VARCHAR)
    })
    List<Device> selectByExample(DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.Device
     *
     * @mbg.generated Sun Jul 29 14:44:38 CEST 2018
     */
    @Select({
        "select",
        "ID, Name, Description",
        "from mob.Device",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="Name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="Description", property="description", jdbcType=JdbcType.VARCHAR)
    })
    Device selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.Device
     *
     * @mbg.generated Sun Jul 29 14:44:38 CEST 2018
     */
    @UpdateProvider(type=DeviceSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Device record, @Param("example") DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.Device
     *
     * @mbg.generated Sun Jul 29 14:44:38 CEST 2018
     */
    @UpdateProvider(type=DeviceSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Device record, @Param("example") DeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.Device
     *
     * @mbg.generated Sun Jul 29 14:44:38 CEST 2018
     */
    @UpdateProvider(type=DeviceSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.Device
     *
     * @mbg.generated Sun Jul 29 14:44:38 CEST 2018
     */
    @Update({
        "update mob.Device",
        "set Name = #{name,jdbcType=VARCHAR},",
          "Description = #{description,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Device record);
}