package com.tvz.mobilnelabapi.mappers.dao;

import com.tvz.mobilnelabapi.model.Measurements;
import com.tvz.mobilnelabapi.model.MeasurementsExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface MeasurementsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.Measurements
     *
     * @mbg.generated Sat Jul 28 14:10:31 CEST 2018
     */
    @SelectProvider(type=MeasurementsSqlProvider.class, method="countByExample")
    long countByExample(MeasurementsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.Measurements
     *
     * @mbg.generated Sat Jul 28 14:10:31 CEST 2018
     */
    @DeleteProvider(type=MeasurementsSqlProvider.class, method="deleteByExample")
    int deleteByExample(MeasurementsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.Measurements
     *
     * @mbg.generated Sat Jul 28 14:10:31 CEST 2018
     */
    @Insert({
        "insert into mob.Measurements (ID, Data, ",
        "DateOfCreation, UserID, ",
        "Username)",
        "values (#{id,jdbcType=INTEGER}, #{data,jdbcType=NVARCHAR}, ",
        "#{dateofcreation,jdbcType=TIMESTAMP}, #{userid,jdbcType=INTEGER}, ",
        "#{username,jdbcType=VARCHAR})"
    })
    int insert(Measurements record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.Measurements
     *
     * @mbg.generated Sat Jul 28 14:10:31 CEST 2018
     */
    @InsertProvider(type=MeasurementsSqlProvider.class, method="insertSelective")
    int insertSelective(Measurements record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.Measurements
     *
     * @mbg.generated Sat Jul 28 14:10:31 CEST 2018
     */
    @SelectProvider(type=MeasurementsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER),
        @Result(column="Data", property="data", jdbcType=JdbcType.NVARCHAR),
        @Result(column="DateOfCreation", property="dateofcreation", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UserID", property="userid", jdbcType=JdbcType.INTEGER),
        @Result(column="Username", property="username", jdbcType=JdbcType.VARCHAR)
    })
    List<Measurements> selectByExampleWithRowbounds(MeasurementsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.Measurements
     *
     * @mbg.generated Sat Jul 28 14:10:31 CEST 2018
     */
    @SelectProvider(type=MeasurementsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER),
        @Result(column="Data", property="data", jdbcType=JdbcType.NVARCHAR),
        @Result(column="DateOfCreation", property="dateofcreation", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="UserID", property="userid", jdbcType=JdbcType.INTEGER),
        @Result(column="Username", property="username", jdbcType=JdbcType.VARCHAR)
    })
    List<Measurements> selectByExample(MeasurementsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.Measurements
     *
     * @mbg.generated Sat Jul 28 14:10:31 CEST 2018
     */
    @UpdateProvider(type=MeasurementsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Measurements record, @Param("example") MeasurementsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.Measurements
     *
     * @mbg.generated Sat Jul 28 14:10:31 CEST 2018
     */
    @UpdateProvider(type=MeasurementsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Measurements record, @Param("example") MeasurementsExample example);
}