package com.tvz.mobilnelabapi.mappers.dao;

import com.tvz.mobilnelabapi.model.Measurementreportimages;
import com.tvz.mobilnelabapi.model.MeasurementreportimagesExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface MeasurementreportimagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.MeasurementReportImages
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    @SelectProvider(type=MeasurementreportimagesSqlProvider.class, method="countByExample")
    long countByExample(MeasurementreportimagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.MeasurementReportImages
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    @DeleteProvider(type=MeasurementreportimagesSqlProvider.class, method="deleteByExample")
    int deleteByExample(MeasurementreportimagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.MeasurementReportImages
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    @Delete({
        "delete from mob.MeasurementReportImages",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.MeasurementReportImages
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    @Insert({
        "insert into mob.MeasurementReportImages (ID, MeasurementID, ",
        "ImageName, Image)",
        "values (#{id,jdbcType=INTEGER}, #{measurementid,jdbcType=INTEGER}, ",
        "#{imagename,jdbcType=VARCHAR}, #{image,jdbcType=NVARCHAR})"
    })
    int insert(Measurementreportimages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.MeasurementReportImages
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    @InsertProvider(type=MeasurementreportimagesSqlProvider.class, method="insertSelective")
    int insertSelective(Measurementreportimages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.MeasurementReportImages
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    @SelectProvider(type=MeasurementreportimagesSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="MeasurementID", property="measurementid", jdbcType=JdbcType.INTEGER),
        @Result(column="ImageName", property="imagename", jdbcType=JdbcType.VARCHAR),
        @Result(column="Image", property="image", jdbcType=JdbcType.NVARCHAR)
    })
    List<Measurementreportimages> selectByExampleWithRowbounds(MeasurementreportimagesExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.MeasurementReportImages
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    @SelectProvider(type=MeasurementreportimagesSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="MeasurementID", property="measurementid", jdbcType=JdbcType.INTEGER),
        @Result(column="ImageName", property="imagename", jdbcType=JdbcType.VARCHAR),
        @Result(column="Image", property="image", jdbcType=JdbcType.NVARCHAR)
    })
    List<Measurementreportimages> selectByExample(MeasurementreportimagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.MeasurementReportImages
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    @Select({
        "select",
        "ID, MeasurementID, ImageName, Image",
        "from mob.MeasurementReportImages",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="MeasurementID", property="measurementid", jdbcType=JdbcType.INTEGER),
        @Result(column="ImageName", property="imagename", jdbcType=JdbcType.VARCHAR),
        @Result(column="Image", property="image", jdbcType=JdbcType.NVARCHAR)
    })
    Measurementreportimages selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.MeasurementReportImages
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    @UpdateProvider(type=MeasurementreportimagesSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Measurementreportimages record, @Param("example") MeasurementreportimagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.MeasurementReportImages
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    @UpdateProvider(type=MeasurementreportimagesSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Measurementreportimages record, @Param("example") MeasurementreportimagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.MeasurementReportImages
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    @UpdateProvider(type=MeasurementreportimagesSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Measurementreportimages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.MeasurementReportImages
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    @Update({
        "update mob.MeasurementReportImages",
        "set MeasurementID = #{measurementid,jdbcType=INTEGER},",
          "ImageName = #{imagename,jdbcType=VARCHAR},",
          "Image = #{image,jdbcType=NVARCHAR}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Measurementreportimages record);
}