package com.tvz.mobilnelabapi.mappers.dao;

import com.tvz.mobilnelabapi.model.Measurements;
import com.tvz.mobilnelabapi.model.MeasurementsExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface MeasurementsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mob.measurements
	 * @mbg.generated  Sat Jul 21 18:14:37 CEST 2018
	 */
	@SelectProvider(type = MeasurementsSqlProvider.class, method = "countByExample")
	long countByExample(MeasurementsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mob.measurements
	 * @mbg.generated  Sat Jul 21 18:14:37 CEST 2018
	 */
	@DeleteProvider(type = MeasurementsSqlProvider.class, method = "deleteByExample")
	int deleteByExample(MeasurementsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mob.measurements
	 * @mbg.generated  Sat Jul 21 18:14:37 CEST 2018
	 */
	@Insert({ "insert into mob.measurements (ID, data)", "values (#{id,jdbcType=INTEGER}, #{data,jdbcType=NVARCHAR})" })
	int insert(Measurements record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mob.measurements
	 * @mbg.generated  Sat Jul 21 18:14:37 CEST 2018
	 */
	@InsertProvider(type = MeasurementsSqlProvider.class, method = "insertSelective")
	int insertSelective(Measurements record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mob.measurements
	 * @mbg.generated  Sat Jul 21 18:14:37 CEST 2018
	 */
	@SelectProvider(type = MeasurementsSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "ID", property = "id", jdbcType = JdbcType.INTEGER),
			@Result(column = "data", property = "data", jdbcType = JdbcType.NVARCHAR) })
	List<Measurements> selectByExampleWithRowbounds(MeasurementsExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mob.measurements
	 * @mbg.generated  Sat Jul 21 18:14:37 CEST 2018
	 */
	@SelectProvider(type = MeasurementsSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "ID", property = "id", jdbcType = JdbcType.INTEGER),
			@Result(column = "data", property = "data", jdbcType = JdbcType.NVARCHAR) })
	List<Measurements> selectByExample(MeasurementsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mob.measurements
	 * @mbg.generated  Sat Jul 21 18:14:37 CEST 2018
	 */
	@UpdateProvider(type = MeasurementsSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") Measurements record, @Param("example") MeasurementsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mob.measurements
	 * @mbg.generated  Sat Jul 21 18:14:37 CEST 2018
	 */
	@UpdateProvider(type = MeasurementsSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") Measurements record, @Param("example") MeasurementsExample example);
}