package com.tvz.mobilnelabapi.mappers.dao;

import com.tvz.mobilnelabapi.model.UserAuthority;
import com.tvz.mobilnelabapi.model.UserAuthorityExample.Criteria;
import com.tvz.mobilnelabapi.model.UserAuthorityExample.Criterion;
import com.tvz.mobilnelabapi.model.UserAuthorityExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class UserAuthoritySqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tvz.user_authority
	 * @mbg.generated  Thu Jul 26 14:06:40 CEST 2018
	 */
	public String countByExample(UserAuthorityExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("tvz.user_authority");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tvz.user_authority
	 * @mbg.generated  Thu Jul 26 14:06:40 CEST 2018
	 */
	public String deleteByExample(UserAuthorityExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("tvz.user_authority");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tvz.user_authority
	 * @mbg.generated  Thu Jul 26 14:06:40 CEST 2018
	 */
	public String insertSelective(UserAuthority record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("tvz.user_authority");
		if (record.getUserId() != null) {
			sql.VALUES("user_id", "#{userId,jdbcType=INTEGER}");
		}
		if (record.getAuthorityId() != null) {
			sql.VALUES("authority_id", "#{authorityId,jdbcType=INTEGER}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tvz.user_authority
	 * @mbg.generated  Thu Jul 26 14:06:40 CEST 2018
	 */
	public String selectByExample(UserAuthorityExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("user_id");
		} else {
			sql.SELECT("user_id");
		}
		sql.SELECT("authority_id");
		sql.FROM("tvz.user_authority");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tvz.user_authority
	 * @mbg.generated  Thu Jul 26 14:06:40 CEST 2018
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		UserAuthority record = (UserAuthority) parameter.get("record");
		UserAuthorityExample example = (UserAuthorityExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("tvz.user_authority");
		if (record.getUserId() != null) {
			sql.SET("user_id = #{record.userId,jdbcType=INTEGER}");
		}
		if (record.getAuthorityId() != null) {
			sql.SET("authority_id = #{record.authorityId,jdbcType=INTEGER}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tvz.user_authority
	 * @mbg.generated  Thu Jul 26 14:06:40 CEST 2018
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("tvz.user_authority");
		sql.SET("user_id = #{record.userId,jdbcType=INTEGER}");
		sql.SET("authority_id = #{record.authorityId,jdbcType=INTEGER}");
		UserAuthorityExample example = (UserAuthorityExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tvz.user_authority
	 * @mbg.generated  Thu Jul 26 14:06:40 CEST 2018
	 */
	protected void applyWhere(SQL sql, UserAuthorityExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}