package com.tvz.mobilnelabapi.model;

import java.io.Serializable;

public class Authority implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tvz.authority.id
	 * @mbg.generated  Thu Jul 26 14:06:40 CEST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tvz.authority.name
	 * @mbg.generated  Thu Jul 26 14:06:40 CEST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tvz.authority
	 * @mbg.generated  Thu Jul 26 14:06:40 CEST 2018
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tvz.authority.id
	 * @return  the value of tvz.authority.id
	 * @mbg.generated  Thu Jul 26 14:06:40 CEST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tvz.authority.id
	 * @param id  the value for tvz.authority.id
	 * @mbg.generated  Thu Jul 26 14:06:40 CEST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tvz.authority.name
	 * @return  the value of tvz.authority.name
	 * @mbg.generated  Thu Jul 26 14:06:40 CEST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tvz.authority.name
	 * @param name  the value for tvz.authority.name
	 * @mbg.generated  Thu Jul 26 14:06:40 CEST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tvz.authority
	 * @mbg.generated  Thu Jul 26 14:06:40 CEST 2018
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Authority other = (Authority) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tvz.authority
	 * @mbg.generated  Thu Jul 26 14:06:40 CEST 2018
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
		return result;
	}
}