package com.tvz.mobilnelabapi.model;

import java.io.Serializable;

public class Authority implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mob.Authority.ID
	 * @mbg.generated  Sun Jul 29 14:44:38 CEST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mob.Authority.Name
	 * @mbg.generated  Sun Jul 29 14:44:38 CEST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mob.Authority.FullName
	 * @mbg.generated  Sun Jul 29 14:44:38 CEST 2018
	 */
	private String fullname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table mob.Authority
	 * @mbg.generated  Sun Jul 29 14:44:38 CEST 2018
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mob.Authority.ID
	 * @return  the value of mob.Authority.ID
	 * @mbg.generated  Sun Jul 29 14:44:38 CEST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mob.Authority.ID
	 * @param id  the value for mob.Authority.ID
	 * @mbg.generated  Sun Jul 29 14:44:38 CEST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mob.Authority.Name
	 * @return  the value of mob.Authority.Name
	 * @mbg.generated  Sun Jul 29 14:44:38 CEST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mob.Authority.Name
	 * @param name  the value for mob.Authority.Name
	 * @mbg.generated  Sun Jul 29 14:44:38 CEST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mob.Authority.FullName
	 * @return  the value of mob.Authority.FullName
	 * @mbg.generated  Sun Jul 29 14:44:38 CEST 2018
	 */
	public String getFullname() {
		return fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mob.Authority.FullName
	 * @param fullname  the value for mob.Authority.FullName
	 * @mbg.generated  Sun Jul 29 14:44:38 CEST 2018
	 */
	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mob.Authority
	 * @mbg.generated  Sun Jul 29 14:44:38 CEST 2018
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Authority other = (Authority) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
				&& (this.getFullname() == null ? other.getFullname() == null
						: this.getFullname().equals(other.getFullname()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mob.Authority
	 * @mbg.generated  Sun Jul 29 14:44:38 CEST 2018
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
		result = prime * result + ((getFullname() == null) ? 0 : getFullname().hashCode());
		return result;
	}
}