package com.tvz.mobilnelabapi.model;

import java.io.Serializable;
import org.json.JSONObject;

import com.fasterxml.jackson.annotation.JsonRawValue;
import java.util.Date;

public class Measurements implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tvz.measurements.ID
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tvz.measurements.Data
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	private String data;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tvz.measurements.DateOfCreation
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	private Date dateofcreation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tvz.measurements.UserID
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tvz.measurements.Username
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tvz.measurements
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tvz.measurements.ID
	 * @return  the value of tvz.measurements.ID
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tvz.measurements.ID
	 * @param id  the value for tvz.measurements.ID
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tvz.measurements.Data
	 * @return  the value of tvz.measurements.Data
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	@JsonRawValue
	public String getData() {
		return data;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tvz.measurements.Data
	 * @param data  the value for tvz.measurements.Data
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	public void setData(String data) {
		this.data = data;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tvz.measurements.DateOfCreation
	 * @return  the value of tvz.measurements.DateOfCreation
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	public Date getDateofcreation() {
		return dateofcreation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tvz.measurements.DateOfCreation
	 * @param dateofcreation  the value for tvz.measurements.DateOfCreation
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	public void setDateofcreation(Date dateofcreation) {
		this.dateofcreation = dateofcreation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tvz.measurements.UserID
	 * @return  the value of tvz.measurements.UserID
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tvz.measurements.UserID
	 * @param userid  the value for tvz.measurements.UserID
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tvz.measurements.Username
	 * @return  the value of tvz.measurements.Username
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tvz.measurements.Username
	 * @param username  the value for tvz.measurements.Username
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tvz.measurements
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Measurements other = (Measurements) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getData() == null ? other.getData() == null : this.getData().equals(other.getData()))
				&& (this.getDateofcreation() == null ? other.getDateofcreation() == null
						: this.getDateofcreation().equals(other.getDateofcreation()))
				&& (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
				&& (this.getUsername() == null ? other.getUsername() == null
						: this.getUsername().equals(other.getUsername()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tvz.measurements
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getData() == null) ? 0 : getData().hashCode());
		result = prime * result + ((getDateofcreation() == null) ? 0 : getDateofcreation().hashCode());
		result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
		result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
		return result;
	}
}