package com.tvz.mobilnelabapi.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class Measurementreportdata implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mob.MeasurementReportData.ID
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mob.MeasurementReportData.MeasurementID
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	private Integer measurementid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mob.MeasurementReportData.ParameterName
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	private String parametername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mob.MeasurementReportData.ParameterValueMin
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	private BigDecimal parametervaluemin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mob.MeasurementReportData.ParameterValueAverage
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	private BigDecimal parametervalueaverage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mob.MeasurementReportData.ParameterValueMax
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	private BigDecimal parametervaluemax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mob.MeasurementReportData.ParameterUnits
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	private String parameterunits;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mob.MeasurementReportData.UseForReport
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	private Boolean useforreport;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table mob.MeasurementReportData
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mob.MeasurementReportData.ID
	 * @return  the value of mob.MeasurementReportData.ID
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mob.MeasurementReportData.ID
	 * @param id  the value for mob.MeasurementReportData.ID
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mob.MeasurementReportData.MeasurementID
	 * @return  the value of mob.MeasurementReportData.MeasurementID
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	public Integer getMeasurementid() {
		return measurementid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mob.MeasurementReportData.MeasurementID
	 * @param measurementid  the value for mob.MeasurementReportData.MeasurementID
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	public void setMeasurementid(Integer measurementid) {
		this.measurementid = measurementid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mob.MeasurementReportData.ParameterName
	 * @return  the value of mob.MeasurementReportData.ParameterName
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	public String getParametername() {
		return parametername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mob.MeasurementReportData.ParameterName
	 * @param parametername  the value for mob.MeasurementReportData.ParameterName
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	public void setParametername(String parametername) {
		this.parametername = parametername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mob.MeasurementReportData.ParameterValueMin
	 * @return  the value of mob.MeasurementReportData.ParameterValueMin
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	public BigDecimal getParametervaluemin() {
		return parametervaluemin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mob.MeasurementReportData.ParameterValueMin
	 * @param parametervaluemin  the value for mob.MeasurementReportData.ParameterValueMin
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	public void setParametervaluemin(BigDecimal parametervaluemin) {
		this.parametervaluemin = parametervaluemin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mob.MeasurementReportData.ParameterValueAverage
	 * @return  the value of mob.MeasurementReportData.ParameterValueAverage
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	public BigDecimal getParametervalueaverage() {
		return parametervalueaverage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mob.MeasurementReportData.ParameterValueAverage
	 * @param parametervalueaverage  the value for mob.MeasurementReportData.ParameterValueAverage
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	public void setParametervalueaverage(BigDecimal parametervalueaverage) {
		this.parametervalueaverage = parametervalueaverage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mob.MeasurementReportData.ParameterValueMax
	 * @return  the value of mob.MeasurementReportData.ParameterValueMax
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	public BigDecimal getParametervaluemax() {
		return parametervaluemax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mob.MeasurementReportData.ParameterValueMax
	 * @param parametervaluemax  the value for mob.MeasurementReportData.ParameterValueMax
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	public void setParametervaluemax(BigDecimal parametervaluemax) {
		this.parametervaluemax = parametervaluemax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mob.MeasurementReportData.ParameterUnits
	 * @return  the value of mob.MeasurementReportData.ParameterUnits
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	public String getParameterunits() {
		return parameterunits;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mob.MeasurementReportData.ParameterUnits
	 * @param parameterunits  the value for mob.MeasurementReportData.ParameterUnits
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	public void setParameterunits(String parameterunits) {
		this.parameterunits = parameterunits;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mob.MeasurementReportData.UseForReport
	 * @return  the value of mob.MeasurementReportData.UseForReport
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	public Boolean getUseforreport() {
		return useforreport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mob.MeasurementReportData.UseForReport
	 * @param useforreport  the value for mob.MeasurementReportData.UseForReport
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	public void setUseforreport(Boolean useforreport) {
		this.useforreport = useforreport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mob.MeasurementReportData
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Measurementreportdata other = (Measurementreportdata) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getMeasurementid() == null ? other.getMeasurementid() == null
						: this.getMeasurementid().equals(other.getMeasurementid()))
				&& (this.getParametername() == null ? other.getParametername() == null
						: this.getParametername().equals(other.getParametername()))
				&& (this.getParametervaluemin() == null ? other.getParametervaluemin() == null
						: this.getParametervaluemin().equals(other.getParametervaluemin()))
				&& (this.getParametervalueaverage() == null ? other.getParametervalueaverage() == null
						: this.getParametervalueaverage().equals(other.getParametervalueaverage()))
				&& (this.getParametervaluemax() == null ? other.getParametervaluemax() == null
						: this.getParametervaluemax().equals(other.getParametervaluemax()))
				&& (this.getParameterunits() == null ? other.getParameterunits() == null
						: this.getParameterunits().equals(other.getParameterunits()))
				&& (this.getUseforreport() == null ? other.getUseforreport() == null
						: this.getUseforreport().equals(other.getUseforreport()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mob.MeasurementReportData
	 * @mbg.generated  Sun Sep 16 22:15:54 CEST 2018
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getMeasurementid() == null) ? 0 : getMeasurementid().hashCode());
		result = prime * result + ((getParametername() == null) ? 0 : getParametername().hashCode());
		result = prime * result + ((getParametervaluemin() == null) ? 0 : getParametervaluemin().hashCode());
		result = prime * result + ((getParametervalueaverage() == null) ? 0 : getParametervalueaverage().hashCode());
		result = prime * result + ((getParametervaluemax() == null) ? 0 : getParametervaluemax().hashCode());
		result = prime * result + ((getParameterunits() == null) ? 0 : getParameterunits().hashCode());
		result = prime * result + ((getUseforreport() == null) ? 0 : getUseforreport().hashCode());
		return result;
	}
}