package com.tvz.mobilnelabapi.model;

import java.io.Serializable;

public class Measurementreportimages implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mob.MeasurementReportImages.ID
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mob.MeasurementReportImages.MeasurementID
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    private Integer measurementid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mob.MeasurementReportImages.ImageName
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    private String imagename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mob.MeasurementReportImages.Image
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mob.MeasurementReportImages
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mob.MeasurementReportImages.ID
     *
     * @return the value of mob.MeasurementReportImages.ID
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mob.MeasurementReportImages.ID
     *
     * @param id the value for mob.MeasurementReportImages.ID
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mob.MeasurementReportImages.MeasurementID
     *
     * @return the value of mob.MeasurementReportImages.MeasurementID
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    public Integer getMeasurementid() {
        return measurementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mob.MeasurementReportImages.MeasurementID
     *
     * @param measurementid the value for mob.MeasurementReportImages.MeasurementID
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    public void setMeasurementid(Integer measurementid) {
        this.measurementid = measurementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mob.MeasurementReportImages.ImageName
     *
     * @return the value of mob.MeasurementReportImages.ImageName
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    public String getImagename() {
        return imagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mob.MeasurementReportImages.ImageName
     *
     * @param imagename the value for mob.MeasurementReportImages.ImageName
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    public void setImagename(String imagename) {
        this.imagename = imagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mob.MeasurementReportImages.Image
     *
     * @return the value of mob.MeasurementReportImages.Image
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mob.MeasurementReportImages.Image
     *
     * @param image the value for mob.MeasurementReportImages.Image
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.MeasurementReportImages
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Measurementreportimages other = (Measurementreportimages) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMeasurementid() == null ? other.getMeasurementid() == null : this.getMeasurementid().equals(other.getMeasurementid()))
            && (this.getImagename() == null ? other.getImagename() == null : this.getImagename().equals(other.getImagename()))
            && (this.getImage() == null ? other.getImage() == null : this.getImage().equals(other.getImage()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.MeasurementReportImages
     *
     * @mbg.generated Tue Oct 02 21:19:12 CEST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMeasurementid() == null) ? 0 : getMeasurementid().hashCode());
        result = prime * result + ((getImagename() == null) ? 0 : getImagename().hashCode());
        result = prime * result + ((getImage() == null) ? 0 : getImage().hashCode());
        return result;
    }
}