package com.tvz.mobilnelabapi.model;

import java.io.Serializable;
import org.json.JSONObject;

import com.fasterxml.jackson.annotation.JsonRawValue;

public class Measurements implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mob.measurements.ID
	 * @mbg.generated  Sat Jul 21 18:14:37 CEST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mob.measurements.data
	 * @mbg.generated  Sat Jul 21 18:14:37 CEST 2018
	 */
	private String data;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table mob.measurements
	 * @mbg.generated  Sat Jul 21 18:14:37 CEST 2018
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mob.measurements.ID
	 * @return  the value of mob.measurements.ID
	 * @mbg.generated  Sat Jul 21 18:14:37 CEST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mob.measurements.ID
	 * @param id  the value for mob.measurements.ID
	 * @mbg.generated  Sat Jul 21 18:14:37 CEST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mob.measurements.data
	 * @return  the value of mob.measurements.data
	 * @mbg.generated  Sat Jul 21 18:14:37 CEST 2018
	 */
	@JsonRawValue
	public String getData() {
		return data;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mob.measurements.data
	 * @param data  the value for mob.measurements.data
	 * @mbg.generated  Sat Jul 21 18:14:37 CEST 2018
	 */
	public void setData(String data) {
		this.data = data;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mob.measurements
	 * @mbg.generated  Sat Jul 21 18:14:37 CEST 2018
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Measurements other = (Measurements) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getData() == null ? other.getData() == null : this.getData().equals(other.getData()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mob.measurements
	 * @mbg.generated  Sat Jul 21 18:14:37 CEST 2018
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getData() == null) ? 0 : getData().hashCode());
		return result;
	}
}