package com.tvz.mobilnelabapi.model;

import java.io.Serializable;

public class UserAuthority implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mob.UserAuthority.UserID
     *
     * @mbg.generated Sat Jul 28 14:10:31 CEST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mob.UserAuthority.AuthorityID
     *
     * @mbg.generated Sat Jul 28 14:10:31 CEST 2018
     */
    private Integer authorityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mob.UserAuthority
     *
     * @mbg.generated Sat Jul 28 14:10:31 CEST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mob.UserAuthority.UserID
     *
     * @return the value of mob.UserAuthority.UserID
     *
     * @mbg.generated Sat Jul 28 14:10:31 CEST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mob.UserAuthority.UserID
     *
     * @param userid the value for mob.UserAuthority.UserID
     *
     * @mbg.generated Sat Jul 28 14:10:31 CEST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mob.UserAuthority.AuthorityID
     *
     * @return the value of mob.UserAuthority.AuthorityID
     *
     * @mbg.generated Sat Jul 28 14:10:31 CEST 2018
     */
    public Integer getAuthorityid() {
        return authorityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mob.UserAuthority.AuthorityID
     *
     * @param authorityid the value for mob.UserAuthority.AuthorityID
     *
     * @mbg.generated Sat Jul 28 14:10:31 CEST 2018
     */
    public void setAuthorityid(Integer authorityid) {
        this.authorityid = authorityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.UserAuthority
     *
     * @mbg.generated Sat Jul 28 14:10:31 CEST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserAuthority other = (UserAuthority) that;
        return (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getAuthorityid() == null ? other.getAuthorityid() == null : this.getAuthorityid().equals(other.getAuthorityid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mob.UserAuthority
     *
     * @mbg.generated Sat Jul 28 14:10:31 CEST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getAuthorityid() == null) ? 0 : getAuthorityid().hashCode());
        return result;
    }
}