package com.tvz.mobilnelabapi.model;

import java.io.Serializable;
import java.util.Arrays;
import java.util.Date;

public class User implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tvz.user.id
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tvz.user.username
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tvz.user.password
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tvz.user.firstname
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	private String firstname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tvz.user.lastname
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	private String lastname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tvz.user.email
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tvz.user.enabled
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	private Boolean enabled;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tvz.user.lastpasswordresetdate
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	private Date lastpasswordresetdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tvz.user
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tvz.user.id
	 * @return  the value of tvz.user.id
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tvz.user.id
	 * @param id  the value for tvz.user.id
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tvz.user.username
	 * @return  the value of tvz.user.username
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tvz.user.username
	 * @param username  the value for tvz.user.username
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tvz.user.password
	 * @return  the value of tvz.user.password
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tvz.user.password
	 * @param password  the value for tvz.user.password
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tvz.user.firstname
	 * @return  the value of tvz.user.firstname
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	public String getFirstname() {
		return firstname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tvz.user.firstname
	 * @param firstname  the value for tvz.user.firstname
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tvz.user.lastname
	 * @return  the value of tvz.user.lastname
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	public String getLastname() {
		return lastname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tvz.user.lastname
	 * @param lastname  the value for tvz.user.lastname
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tvz.user.email
	 * @return  the value of tvz.user.email
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tvz.user.email
	 * @param email  the value for tvz.user.email
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tvz.user.enabled
	 * @return  the value of tvz.user.enabled
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	public Boolean getEnabled() {
		return enabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tvz.user.enabled
	 * @param enabled  the value for tvz.user.enabled
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tvz.user.lastpasswordresetdate
	 * @return  the value of tvz.user.lastpasswordresetdate
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	public Date getLastpasswordresetdate() {
		return lastpasswordresetdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tvz.user.lastpasswordresetdate
	 * @param lastpasswordresetdate  the value for tvz.user.lastpasswordresetdate
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	public void setLastpasswordresetdate(Date lastpasswordresetdate) {
		this.lastpasswordresetdate = lastpasswordresetdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tvz.user
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		User other = (User) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getUsername() == null ? other.getUsername() == null
						: this.getUsername().equals(other.getUsername()))
				&& (this.getPassword() == null ? other.getPassword() == null
						: this.getPassword().equals(other.getPassword()))
				&& (this.getFirstname() == null ? other.getFirstname() == null
						: this.getFirstname().equals(other.getFirstname()))
				&& (this.getLastname() == null ? other.getLastname() == null
						: this.getLastname().equals(other.getLastname()))
				&& (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
				&& (this.getEnabled() == null ? other.getEnabled() == null
						: this.getEnabled().equals(other.getEnabled()))
				&& (this.getLastpasswordresetdate() == null ? other.getLastpasswordresetdate() == null
						: this.getLastpasswordresetdate().equals(other.getLastpasswordresetdate()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tvz.user
	 * @mbg.generated  Thu Jul 26 22:42:58 CEST 2018
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
		result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
		result = prime * result + ((getFirstname() == null) ? 0 : getFirstname().hashCode());
		result = prime * result + ((getLastname() == null) ? 0 : getLastname().hashCode());
		result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
		result = prime * result + ((getEnabled() == null) ? 0 : getEnabled().hashCode());
		result = prime * result + ((getLastpasswordresetdate() == null) ? 0 : getLastpasswordresetdate().hashCode());
		return result;
	}
}